### ISSUE TITLE
How to get the iframe code for a private video with dailymotion api

### ISSUE THREAD

**Issue by yoyoy** [dailymotion/dailymotion-sdk-php#36]
I would like to use dailymotion api to get infos of my own private videos. SO ... I have a Dailymotion account I have created an API key and secret key I downloaded the PHP class I would like to get infos of my privates videos to diplay it on my website...

So i think I need to authenticate my account and after get the code... but it does not work :'( Please could you give me a sample code to do this ?

my test code is like that for now

```php
<?php 
error_reporting(E_ALL & ~E_NOTICE);
ini_set('display_errors', 1);

$apiKey = 'xxxx';
$apiSecret = 'xxxx';
require_once 'Dailymotion.php';
// Instanciate the PHP SDK.
$api = new Dailymotion();

// Tell the SDK what kind of authentication you'd like to use.
// Because the SDK works with lazy authentication, no request is performed at this point.
$api->setGrantType(Dailymotion::GRANT_TYPE_AUTHORIZATION, $apiKey, $apiSecret);

$api = new Dailymotion();
try
{
$result = $api->get(
'/video/privateVideoId',
array('fields' => array('id', 'title', 'owner'))
);

}
catch (DailymotionAuthRequiredException $e)
{
echo $e->getMessage();
// If the SDK doesn't have any access token stored in memory, it tries to
// redirect the user to the Dailymotion authorization page for authentication.
//return header('Location: ' . $api->getAuthorizationUrl());
}
catch (DailymotionAuthRefusedException $e)
{
echo $e->getMessage();
// Handle the situation when the user refused to authorize and came back here.
// <YOUR CODE>
}

trace($result);

function trace($d) {
echo '<pre>';
var_dump($d);
echo '</pre>';
}
?>
```
and the result is : This user is not allowed to access this video.

so i think there is a problem with authentication ... but i do not understant how to do that only with php

thanks a lot for your help

**Comment by MathildeS** [comment]
You're right, the way you do the authentication is not right. 
This is what you're doing: 
```
$api = new Dailymotion();

// Tell the SDK what kind of authentication you'd like to use.
// Because the SDK works with lazy authentication, no request is performed at this point.
$api->setGrantType(Dailymotion::GRANT_TYPE_AUTHORIZATION, $apiKey, $apiSecret);

$api = new Dailymotion();
``` 

the second `$api = new Dailymotion();` you're passing re-instantiates the SDK, so the lines you're wrote before have no impact. Hence no authentication is done. 
=> you should remove this line of code. 

If no user is currently logged, you catch `catch (DailymotionAuthRequiredException $e)` but do nothing. You should redirect the user to the Dailymotion authorization page for authentication 
=> un-comment the piece of code below: `return header('Location: ' . $api->getAuthorizationUrl());`

Anyway, this is all detailed here : https://developer.dailymotion.com/tools/sdks#sdk-php-grant-authorization
