### ISSUE TITLE
SDK 1.6.3 - Little bug with 'open_basedir' handling

### ISSUE THREAD

**Issue by EricSivilog** [dailymotion/dailymotion-sdk-php#38]
Hi there,

I have just followed Dailymotion's advice regarding SSLv3 vulnerability and updated our websites to SDK 1.6.3. However, I then got the following warning:

Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in G:\Apache2.4\htdocs\pfxfwf\dm\Dailymotion.phpon line 842

There's actually a little mistake on line 833 of "Dailymotion.php" which causes the warning on line 842 :

        if (!filter_var(ini_get('open_basedir'), FILTER_VALIDATE_BOOLEAN) && !filter_var(ini_get('safe_mode'), FILTER_VALIDATE_BOOLEAN))

The filter_var function is used on the result of ini_get(‘open_basedir’) which is of type string. Hence the call to filter_var with type FILTER_VALIDATE_BOOLEAN always returns FALSE and option CURLOPT_FOLLOWLOCATION is always set when calling curl_setopt_array on ligne 842.

Line 833 should be replaced by :

        if ((ini_get('open_basedir')=='') && (!filter_var(ini_get('safe_mode'), FILTER_VALIDATE_BOOLEAN)))

Since PHP 5.3 function ini_get can return FALSE if the requested directive has not been specified, but the ==’’ test will return TRUE if that's the case.

Is it possible to fix this in the next SDK update?

Thanks!

**Comment by NykO18** [comment]
You are absolutely right, I just pushed a fix in the [`follow_redirects_fix`](https://github.com/dailymotion/dailymotion-sdk-php/tree/follow_redirects_fix) branch. Please comment/advise on the pull request here: https://github.com/dailymotion/dailymotion-sdk-php/pull/40

**Comment by EricSivilog** [comment]
NykO, using FILTER_NULL_ON_FAILURE is a great idea, didn't think about it. :+1:

**Comment by NykO18** [comment]
Yes, it did the job wonderfully in my tests by replacing the `open_basedir` value with random stuff. So I kept it simple.

**Comment by NykO18** [comment]
I just pushed the fix to master at https://github.com/dailymotion/dailymotion-sdk-php/commit/e95f8e9876cb9433beca6fd4616d08326a6ef135
Feel free to patch with this version right away while we wait for more fixes before really releasing 1.6.4.
