### ISSUE TITLE
Dailymotion API gives me an improper URL

### ISSUE THREAD

**Issue by syamvilakudy** [dailymotion/dailymotion-sdk-php#42]
I have integrated PHP SDK of Dailymotion  in my website.

I have fetched stream_h264_hq_url by this api ( both Local and Live ). It's woks fine in Local Apache but didn't work in live website.

I my live website, Dailymotion API gives me an improper URL.

**Comment by NykO18** [comment]
Did you check the documentation relative to this field?
> URL of the high quality WVGA video stream (480p, ~845 kbps). Without an access token this field contains `null`, the Dailymotion user associated with the access token must be the owner of the video. This field is rate limited. **The returned url is secured: it can only be consumed by the user who made the query and it expires after a certain time.**

**Comment by syamvilakudy** [comment]
@NykO18, I have got stream url ( not null ) by using PHP SDK in live,  but this url is blank. I checked in my local machine, then i have got correct url but not in live

**Comment by MathildeS** [comment]
Hi, as NykO18 said, the returned url is secured: it is signed so **it can only be consumed by the machine which did the API call**. So only your server, that performed the API call, can read the stream.

**Comment by syamvilakudy** [comment]
Ok @NykO18 and @MathildeS , let me check

**Comment by syamvilakudy** [comment]
Then how can i assign the stream url to my custom HTML5 video tag. Is it possible ?. 

My need is look like this

$result = $api->get(
'/video/x2pw9ox',
array('fields' => array('id', 'title', 'owner','stream_h264_hq_url'))
);

<video width="400" controls>
  <source src="<?php echo $result ['stream_h264_hq_url'] ?>" type="video/mp4">
</video>

**Comment by MathildeS** [comment]
hi @syamvilakudy we recommend you to use dailymotion player to play videos hosted on our plateform. 
As we say in the field description (https://developer.dailymotion.com/documentation#video-stream_h264_hq_url-field): "This field is rate limited. The returned url is secured: it can only be consumed by the user who made the query and it expires after a certain time." 

For example, you can request the [`embed_html` field](https://developer.dailymotion.com/documentation#video-embed_html-field) to obtain the embed code.
