### ISSUE TITLE
Dailymotion TransportException

### ISSUE THREAD

**Issue by Grandbras** [dailymotion/dailymotion-sdk-php#44]
Hi,

I try to upload video with API but I now have an SSL error : 

Uncaught exception 'DailymotionTransportException' with message 'Problem with the SSL CA cert (path? access rights?)'

I try to chmod the cert file, to set curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, false), nothing work.
I'm using curl_setopt ($ch, CURLOPT_CAINFO, xxxxx) and check existence of the dm_ca_chain_bundle.crt file.
(I use to have this work fine for a few month but begin to bug a few weeks ago)

Any ideas ?
:)
Regards,
Gb.

**Comment by MathildeS** [comment]
This is directly a cURL error, you can check those answers : 
- http://stackoverflow.com/questions/7179216/php-problem-with-the-ssl-ca-cert-path-access-rights
- http://stackoverflow.com/questions/15135834/php-curl-curlopt-ssl-verifypeer-ignored
 
do they help?

**Comment by MathildeS** [comment]
Another idea was to update the SDK you're using to make sure you're using the latest version. 
Closing the issue as no answer since June.
