### ISSUE TITLE
Upload No Longer Working

### ISSUE THREAD

**Issue by mrpepik** [dailymotion/dailymotion-sdk-php#48]
Hi Guys,

I hope someone can provide some guidance, up until recently, I was able to upload via a set of scripts I put together, it uses a different redirect_uri than the authorization redirect_uri that I have setup.  

I get the error:
error=redirect_uri_mismatch&error_description=This+`redirect_uri'+(dailymotion_uploadvideo2.php)+isn't+allowed+by+`client_id'+configuration.

When I wrote the scripts originally and testing afterwards, this worked.  I am wondering why it doesn't work now? 

Any suggestions on what to check?

Thanks

Joe

**Comment by MathildeS** [comment]
Hi, 

Make sure the redirect_uri used matches your callback url (the one you set on your api key at http://www.dailymotion.com/settings/developer). 

If that does not help: when did that stop working? Couldn't it be linked to any modification on your script or on the callback url? 

Mathilde

**Comment by mrpepik** [comment]
Hi Mathilde,

This was working up to a couple weeks ago, we are still developing the rest of the site out and I am just going through and reviewing the API's.  I have one script that handles the authentication and grabs the Access Token, Refresh Token, and User ID.  Then I have an upload script that posts the video and video info up to Dailymotion and returns the Video info so I can store it in our database.  I am using Dailymotion::GRANT_TYPE_AUTHORIZATION in both my authorization and my upload scripts, is there a way to use the Access Token and Refresh Token to just refresh the cookie and session info?

If I re-authenticate and have a fresh access token, I am able to use my scripts to upload to Dailymotion.

Thanks

Joe

**Comment by mrpepik** [comment]
Hi Mathilde,

I decided to merge everything into a single file and its now working fine.

Thanks

Joe
