### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by chudiep1511** [dailymotion/dailymotion-sdk-php#51]
Hi dailymotion,
My code:
api = new Dailymotion();

 $api->setGrantType(
            Dailymotion::GRANT_TYPE_PASSWORD,
            $apiKey,
            $apiSecret,
            array('read', 'write', 'delete', 'manage_videos'),
            array('username' => $testUser, 'password' => $testPassword)
        );

        $url = $api->uploadFile('a.mp4');

        $result = $api->post('/me/videos', array('url' => $url));

Get Error mes:

Fatal error: Uncaught exception 'DailymotionTransportException' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\Dailymotion.php:877 Stack trace: #0 C:\xampp\htdocs\Dailymotion.php(727): Dailymotion->httpRequest('https://api.dai...', Array, NULL, NULL, Array, true) #1 C:\xampp\htdocs\Dailymotion.php(591): Dailymotion->oauthTokenRequest(Array) #2 C:\xampp\htdocs\Dailymotion.php(404): Dailymotion->getAccessToken() #3 C:\xampp\htdocs\Dailymotion.php(356): Dailymotion->call('GET /file/uploa...', Array) #4 C:\xampp\htdocs\Dailymotion.php(326): Dailymotion->get('/file/upload', Array) #5 C:\xampp\htdocs\index2.php(21): Dailymotion->uploadFile('a.mp4') #6 {main} thrown in C:\xampp\htdocs\Dailymotion.php on line 877

How can i fix it?

**Comment by hhitch** [comment]
did you find the appropriate solution?

**Comment by yourchoice** [comment]
i have similar pronblem
