### ISSUE TITLE
invalid autorization code with curl 7.47 and php7.07

### ISSUE THREAD

**Issue by rush93** [dailymotion/dailymotion-sdk-php#53]
Hi,

We've go a first error `No Url Set`and commenting CURLOPT_PROXY and CURLOPT_PROXYUSERPWD curl seems now OK but we've got an 

<<< [https://api.dailymotion.com/oauth/token] <<<
stdClass Object
(
    [error] => invalid_grant
    [error_description] => Invalid authorization code.
)

Could u help us to fix. Same code with same params work on another env with curl 7.35

**Comment by Zebraslive** [comment]
@rush93 sorry for asking, but can you get uploads to work when using proxy? I'm guessing none of the contributors will be helping since this was posted in 2016 and is still open.
