### ISSUE TITLE
How to use proxy with api call?

### ISSUE THREAD

**Issue by Zebraslive** [dailymotion/dailymotion-sdk-php#54]
I'm trying to upload a video with a proxy. I keep getting errors after I set the proxy. 

I get this error when connecting successfully to api.
Fatal error: Uncaught exception 'DailymotionApiException' with message 'Invalid API server response'

any idea why this happens?
Uploading without proxy works fine though.

**Comment by Zebraslive** [comment]
I don't think they allow proxies to be used anymore. 
I tried many different proxies and proxy types.
maybe message them directly and ask about it. If you do find anything please let me know.

**Comment by Zebraslive** [comment]
> Did you solve the problem?
> I'm having the same problem.

I don't think they allow proxies to be used anymore. 
I tried many different proxies and proxy types.
maybe message them directly and ask about it. If you do find anything please let me know.

**Comment by nicoferron** [comment]
Hello @Zebraslive,

Can you try to replace the $options varible on line 832 of the Dailymotion.php file by this one:
```php
$options = array(
            CURLOPT_CONNECTTIMEOUT => $this->connectionTimeout,
            CURLOPT_TIMEOUT        => $this->timeout,
            CURLOPT_PROXY          => $this->proxy,
            CURLOPT_PROXYTYPE      => CURLPROXY_SOCKS5,
            CURLOPT_PROXYUSERPWD   => $this->proxyCredentials,
            CURLOPT_USERAGENT      => sprintf('Dailymotion-PHP/%s (PHP %s; %s)', self::VERSION, PHP_VERSION, php_sapi_name()),
            CURLOPT_HEADER         => true,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_URL            => $url,
            CURLOPT_HTTPHEADER     => $headers,
            CURLOPT_POSTFIELDS     => $payload,
            CURLOPT_NOPROGRESS     => !($this->debug && is_array($payload) && array_key_exists('file', $payload)),
        );
```
(just the key/value CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5 is added to the $options array)
It possibly fix the problem by specifying the proxy type to "socks5" as default value is HTTP.
If this option is needed we can add this feature for you and other users.

Regards,
Dailymotion team.
