### ISSUE TITLE
This method can only be used with AUTHORIZATION grant type

### ISSUE THREAD

**Issue by pdolinaj** [dailymotion/dailymotion-sdk-php#55]
I am trying to retrieve a video by ID (not belonging to me) using either GRANT_TYPE_PASSWORD (using my own credentials) or GRANT_TYPE_CLIENT_CREDENTIALS.

However, I receive this error: This method can only be used with AUTHORIZATION grant type

I can't use AUTHORIZATION grant type since my jobs are automated jobs running via CLI so I can't redirect users to page where they would grant access.

Is there a workaround for this?

**Comment by nicoferron** [comment]
Hello @pdolinaj,
I think I found something that could help you in the documentation: [Here](https://developer.dailymotion.com/tools/sdks#sdk-php-overloading)
