### ISSUE TITLE
Invalid refresh token

### ISSUE THREAD

**Issue by leonardop21** [dailymotion/dailymotion-sdk-php#57]
Hello, devs.

I'm having trouble uploading videos to Dailymotion. The first upload works, when I tried to send a second video I get an error message, and so on, one video is sent and the other one fails. The error message is:

"Invalid refresh token"

My code

`             
      $url = $request->file("file");
$api = new Dailymotion();
$api->setGrantType(
Dailymotion::GRANT_TYPE_PASSWORD,
"xxxxxxxxx",
 "xxxxxxxx",
array("manage_videos","userinfo","manage_playlists","manage_user_settings","manage_applications"),
array(
	 "username" => "xxx@xxx.com.br",
	 "password" => "xxx",
));
$api->logout();
$videoUrl = $api->uploadFile($url);

$result = $api->post(
	 "/me/videos",
	 array("url" => $videoUrl, "title" =>"teste de vídeo"
));

`

**Comment by SuperToma** [comment]
Hi Leonardo,

1. Can you try this code but without the line :
```$api->logout();``` 

I think it would be better.

2. Did you add this line by yourself or have you find it in the API documentation ?
We can update the documentation if needed to be more clear.

Regards.

**Comment by leonardop21** [comment]
Thanks for the reply SuperToma. Found in the documentation. Said to update the scope of permissions of the 0auth, it was necessary to call the logout function.

If I try to upload without calling the $api method-> logout (); get a permission error, something close to the Required manage_videos ": scopes, however, I'm sending manage_videos in scope.According to documentation, $api-> logout (); updates the session and can work without problems

Will try again without the method logout (); sending news in brief

**Comment by SuperToma** [comment]
You need to call the logout() function only for upgrade the scope of an existing session.
Maybe the end-user didn't allow you to manage his videos.
You can give us your API key (and not the secret), we will try your code.

**Comment by leonardop21** [comment]
Thanks @SuperToma, your response was of great value, I was able to upload several videos in sequence after removing the logout () method.

In the documentation it could be clearer, use the function just to clear an existing session ie just use only once and then remove the logout.

Helped me a lot.
