### ISSUE TITLE
Fatal error: Class 'PHPUnit_Framework_TestCase' not found 

### ISSUE THREAD

**Issue by kaviyarasu34** [dailymotion/dailymotion-sdk-php#58]
I am using php 7.0.10 in my wamp server I am trying to upload videos to dailymotion using php sdk files. When i run the script it is showing the output as in image. Also using this code PHPUnit/Framework/TestCase also displaying same error.
![php-test-case](https://user-images.githubusercontent.com/41732151/45916766-e44ecf80-be88-11e8-9e23-4ad750c805e2.png)

**Comment by SuperToma** [comment]
Hi @kaviyarasu34,

For implementation question please use stackoverflow.
We replied you here : https://stackoverflow.com/questions/52311034/fatal-error-class-phpunit-framework-testcase-not-found-2018-error/52476533#52476533

Regards.

**Comment by kaviyarasu34** [comment]
Thank you.
