### ISSUE TITLE
Upload Limit or Video Length Limit Check Problem

### ISSUE THREAD

**Issue by oguzdelioglu** [dailymotion/dailymotion-sdk-php#60]
The problem that I mentioned in the title is as follows.

Current System
Upload Video->Upload Video Completed->Check Daily Upload Limit and if yes return error | or Video file size big (TimeLength or MB) 

I think it should be that way.
Check file size or length and check Daily upload limit (if okey go to upload else return error) -> Upload Video->Upload Video Completed

I think it would be better if it was the way I suggested.

If the system is such as I suggest, please specify it.

**Comment by nicoferron** [comment]
Hello @oguzdelioglu ,

The upload feature is generic, we don't check your video upload limits here, they are checked at the video creation. You can check on your side your limits using 
```php
$result = $api->get(
        '/me',
        array('fields' => array('limits')
    );
```
 before using the uploadFile() method.

Regards,

**Comment by oguzdelioglu** [comment]
> Hello @oguzdelioglu ,
> 
> The upload feature is generic, we don't check your video upload limits here, they are checked at the video creation. You can check on your side your limits using
> 
> ```
> $result = $api->get(
>         '/me',
>         array('fields' => array('limits'))
>     );
> ```
> 
> before using the uploadFile() method.
> 
> Regards,

That's exactly what I'm talking about.Let him automatically check if he has crossed the border before uploading the video.

For example, it uploads a 2GB file first, then checks it.
This is both harmful to the dailymotion servers and is a waste of time for the user.

Do you have a different view on this?
Thanks.
