### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by zivisor** [dailymotion/dailymotion-sdk-php#61]
Hi,
My code:
`<?php
include("./Dailymotion.php");
$api = new Dailymotion();
$username = "---username---";
$password = "---password---";
$apiKey = "---apikey---";
$apiSecret = "---apisecret---";
$api->setGrantType(3, $apiKey,$apiSecret,array('read', 'write', 'delete', 'manage_videos'),array('username' => $username,'password' => $password));
$result = $api->get('/me/videos',array('fields' => array('id', 'title', 'owner')));
print_r($result);`

But i got error
`PHP Fatal error:  Uncaught DailymotionAuthException: Invalid credentials. in /home/test/Dailymotion.php:737
Stack trace:
#0 /home/test/Dailymotion.php(590): Dailymotion->oauthTokenRequest(Array)
#1 /home/test/Dailymotion.php(404): Dailymotion->getAccessToken()
#2 /home/test/Dailymotion.php(356): Dailymotion->call('GET /me/videos', Array)
#3 /home/test/index.php(11): Dailymotion->get('/me/videos', Array)
#4 {main}
  thrown in /home/test/Dailymotion.php on line 737`

**Comment by nicoferron** [comment]
Hello @zivisor ,

It seems you have made a typo in your credentials. 
Have you tried to login on the website https://dailymotion.com with the same credentials ?
If they didn't worked, please reach out to the support: https://faq.dailymotion.com

Regards
