### ISSUE TITLE
Error in PHP 8

### ISSUE THREAD

**Issue by esmultivac** [dailymotion/dailymotion-sdk-php#69]
The function get_magic_quotes_gpc() doesn't exist in PHP8, so the line 661 in Dailymotion.php should be:

`trim((function_exists("get_magic_quotes_gpc") && get_magic_quotes_gpc() ? stripslashes($cookieValue) : $cookieValue), '"'),`

**Comment by nicoferron** [comment]
Hello @esmultivac , 
Usage of get_magic_quotes_gpc() function has already been removed on [version 1.6.7](https://github.com/dailymotion/dailymotion-sdk-php/blob/2d2223b1960cfe9495576ad79e4c51a30e7fc243/Dailymotion.php#L696)

**Comment by esmultivac** [comment]
Newest version here and in composer seems to be 1.6.5. How can I update?
