### ISSUE TITLE
Return video id after upload

### ISSUE THREAD

**Issue by gtraxx** [dailymotion/dailymotion-sdk-php#74]
Hi, 
I created a system to upload a video on dailymotion and I would like to return the ID (video id) of this one just after sending.
Do you have an example ?
I will build the link based on this ID

**Comment by nicoferron** [comment]
Hello @gtraxx, based on [this upload code sample](https://developers.dailymotion.com/upload/#samples) you can retrieve your video ID in result of the `post` method as it's a default video field. 
Example:

```
$url = $api->uploadFile('/path/to/your/video.mp4');
$result = $api->post(
    '/user/<CHANNEL_ID>/videos',
    array(
        'url'       => $url,
        'title'     => 'My Title',
        'tags'      => 'add,your,tags',
        'channel'   => 'videogames',
        'published' => true,
        'is_created_for_kids' => false,
    )
);
var_dump($result['id']);
```

**Comment by gtraxx** [comment]
thanks :D
